#!/bin/bash

##################################################
# Project : Server Health Monitor
# Author  : Vishnu Tomar
# Purpose : Monitor CPU, Memory and Disk usage
##################################################

# ==========================
# Configuration
# ==========================

CPU_THRESHOLD=80
MEMORY_THRESHOLD=90
DISK_THRESHOLD=90

# Replace with your email address
EMAILS=(
	"vishnu@unicloud.co"
	"akhil@unicloud.co"
)

# ==========================
# Server Information
# ==========================

HOSTNAME=$(hostname)
CURRENT_TIME=$(date '+%Y-%m-%d %H:%M:%S')

# ==========================
# Functions
# ==========================

# Get CPU usage percentage
get_cpu_usage() {
    top -bn1 | awk -F',' '/Cpu/ {
        gsub(" id", "", $4)
        print int(100 - $4)
    }'
}

# Get Memory usage percentage
get_memory_usage() {
    free | awk '/Mem:/ {
        printf("%.0f", $3/$2 * 100)
    }'
}

# Get Disk usage percentage of the root filesystem
get_disk_usage() {
    df / | tail -1 | awk '{print $5}' | tr -d '%'
}

# Write server health to log file
write_log() {

    LOG_FILE="logs/health-$(date +%F).log"

    echo "$CURRENT_TIME | HOST:$HOSTNAME | CPU:${CPU_USAGE}%($CPU_STATUS) | MEM:${MEMORY_USAGE}%($MEMORY_STATUS) | DISK:${DISK_USAGE}%($DISK_STATUS)" >> "$LOG_FILE"

}

send_email_alert() {

    SUBJECT="🚨 Server Health Alert | Host: $HOSTNAME"

    BODY=$(cat <<EOF
============================================================
                  SERVER HEALTH ALERT
============================================================

Server      : $HOSTNAME
Timestamp   : $CURRENT_TIME

============================================================
RESOURCE             USAGE             STATUS
============================================================
CPU                  ${CPU_USAGE}%               ${CPU_STATUS}
Memory               ${MEMORY_USAGE}%               ${MEMORY_STATUS}
Disk                 ${DISK_USAGE}%               ${DISK_STATUS}
============================================================

Configured Thresholds

- CPU Threshold      : ${CPU_THRESHOLD}%
- Memory Threshold   : ${MEMORY_THRESHOLD}%
- Disk Threshold     : ${DISK_THRESHOLD}%

============================================================
ACTION REQUIRED

One or more resources have exceeded the configured threshold.

Please investigate the server immediately.

============================================================
Generated by Server Health Monitor
EOF
)

    for EMAIL in "${EMAILS[@]}"
    do
        echo "$BODY" | mail -s "$SUBJECT" "$EMAIL"
    done
}
#    BODY="
#Server Health Alert

#Hostname : $HOSTNAME
#Time     : $CURRENT_TIME

#CPU Usage    : ${CPU_USAGE}% [$CPU_STATUS]
#Memory Usage : ${MEMORY_USAGE}% [$MEMORY_STATUS]
#Disk Usage   : ${DISK_USAGE}% [$DISK_STATUS]

#Please check the server immediately.
#"

#    for EMAIL in "${EMAILS[@]}"
#    do
#        echo "$BODY" | mail -s "$SUBJECT" "$EMAIL"
#    done
#}

#BODY=$(cat <<EOF
#========================================================
#             SERVER HEALTH ALERT
#========================================================

#Host        : $HOSTNAME
#Timestamp   : $CURRENT_TIME

#--------------------------------------------------------
#RESOURCE          USAGE        		STATUS
#--------------------------------------------------------
#CPU              ${CPU_USAGE}%         ${CPU_STATUS}
#Memory           ${MEMORY_USAGE}%      ${MEMORY_STATUS}
#Disk             ${DISK_USAGE}%        ${DISK_STATUS}
#--------------------------------------------------------

#Thresholds
#-----------

#CPU        : ${CPU_THRESHOLD}%
#Memory     : ${MEMORY_THRESHOLD}%
#Disk       : ${DISK_THRESHOLD}%

#========================================================

#This alert was generated automatically by
#Server Health Monitor.

#Please investigate the server if any resource
#has exceeded its configured threshold.

#========================================================

#EOF
#)





# Display server health
#
#
#

display_status() {

    echo
    echo "========================================"
    echo "      SERVER HEALTH MONITOR"
    echo "========================================"

    echo "Hostname      : $HOSTNAME"
    echo "Time          : $CURRENT_TIME"

    echo "----------------------------------------"

    echo "CPU Usage     : ${CPU_USAGE}%    [$CPU_STATUS]"
    echo "Memory Usage  : ${MEMORY_USAGE}%    [$MEMORY_STATUS]"
    echo "Disk Usage    : ${DISK_USAGE}%    [$DISK_STATUS]"

    echo "========================================"
}

# ==========================
# Collect Metrics
# ==========================

CPU_USAGE=$(get_cpu_usage)
MEMORY_USAGE=$(get_memory_usage)
DISK_USAGE=$(get_disk_usage)

# ==========================
# Check Thresholds
# ==========================

CPU_STATUS="OK"
MEMORY_STATUS="OK"
DISK_STATUS="OK"

if [ "$CPU_USAGE" -ge "$CPU_THRESHOLD" ]; then
    CPU_STATUS="WARNING"
fi

if [ "$MEMORY_USAGE" -ge "$MEMORY_THRESHOLD" ]; then
    MEMORY_STATUS="WARNING"
fi

if [ "$DISK_USAGE" -ge "$DISK_THRESHOLD" ]; then
    DISK_STATUS="WARNING"
fi

# ==========================
# Display Server Health
# ==========================

#echo
#echo "========================================"
#echo "      SERVER HEALTH MONITOR"
#echo "========================================"

#echo "Hostname      : $HOSTNAME"
#echo "Time          : $CURRENT_TIME"

#echo "----------------------------------------"

#echo "CPU Usage     : ${CPU_USAGE}%    [$CPU_STATUS]"
#echo "Memory Usage  : ${MEMORY_USAGE}%    [$MEMORY_STATUS]"
#echo "Disk Usage    : ${DISK_USAGE}%    [$DISK_STATUS]"

# ==========================
# Logging
# ==========================

#LOG_FILE="logs/health.log"

#echo "$CURRENT_TIME | HOST:$HOSTNAME | CPU:${CPU_USAGE}%($CPU_STATUS) | MEM:${MEMORY_USAGE}%($MEMORY_STATUS) | DISK:${DISK_USAGE}%($DISK_STATUS)" >> "$LOG_FILE"

# Write log entry

#write_log

#echo "========================================"
#
#
#
# ==========================
# Display Server Health
# ==========================

display_status

# ==========================
# Logging
# ==========================

write_log




if [[ "$CPU_STATUS" == "WARNING" || \
      "$MEMORY_STATUS" == "WARNING" || \
      "$DISK_STATUS" == "WARNING" ]]
then
    send_email_alert
fi

echo "========================================"
